FROM python:3.12-slim

RUN apt-get update
RUN apt-get install -y --no-install-recommends git build-essential
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# RUN apt-get update && \
#     apt-get install -y --no-install-recommends git build-essential && \
#     apt-get clean && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY project/ .

