# ===== Build Stage =====
FROM python:3.12-slim AS build

RUN apt-get update && \
    apt-get install -y --no-install-recommends git build-essential && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:0.6.13 /uv /uvx /bin/
ENV PATH="/root/.local/bin/:$PATH"

COPY requirements.txt .
RUN uv pip install --system -r requirements.txt


# ===== Final Stage =====
FROM python:3.12-slim

COPY --from=build /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=build /usr/local/bin /usr/local/bin
COPY project/ .

CMD ["uvicorn", "app:app"]
