FROM python:3.12-slim

RUN apt-get update
RUN apt-get install -y --no-install-recommends git build-essential

COPY . .
RUN pip install --no-cache-dir -r requirements.txt


# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt
# COPY project/ .