# ===== Build Stage =====
FROM python:3.12-slim AS build

RUN apt-get update && \
    apt-get install -y --no-install-recommends git build-essential && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt


# ===== Final Stage =====
FROM python:3.12-slim

COPY --from=build /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH

WORKDIR /app
COPY project/ .

CMD ["uvicorn", "app:app"]
